/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package overview

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
    @Test fun testAppHasAGreeting() {
        assertNotNull("not null", "a string is not null")
    }
}
